spring:
  cassandra:
    keyspace-name: customers
    connection:
      init-query-timeout: PT10S
      connect-timeout: PT10S
    request:
      timeout: PT10S
    session-name: reactive-cassy

  jackson:
    default-property-inclusion: NON_NULL

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
  netty:
    connection-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

logging:
  level:
    com.datastax: DEBUG
    org.springframework.data.cassandra: DEBUG
    org.springframework.hateoas: DEBUG

---

spring:
  config:
    activate:
      on-profile: cloud
  cassandra:
    ssl:
      enabled: true
    contact-points: ${vcap.services.reactive-cassy-secrets.credentials.CONTACT_POINT}
    port: ${vcap.services.reactive-cassy-secrets.credentials.PORT}
    username: ${vcap.services.reactive-cassy-secrets.credentials.USERNAME}
    password: ${vcap.services.reactive-cassy-secrets.credentials.PASSWORD}
    connection:
      init-query-timeout: PT10S
      connect-timeout: PT10S
    request:
      timeout: PT10S
    session-name: reactive-cassy
---

spring:
  config:
    activate:
      on-profile: docker
  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    username: cassandra
    password: cassandra
    connection:
      init-query-timeout: PT10S
      connect-timeout: PT10S
    request:
      timeout: PT10S
    session-name: reactive-cassy
